# -*- mode: ruby -*-
# vi: set ft=ruby :

system("ansible-galaxy install -r ../roles/requirements.yml -p ./roles/ --force")

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox"
  config.vm.network :private_network, ip: "10.1.1.11"
  #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
  config.vm.synced_folder ".", "/vagrant", disabled: true


  if Vagrant.has_plugin?("vagrant-hostmanager")
      config.hostmanager.enabled = true
      config.hostmanager.manage_host = true
  end

  # Create the "toolbox" box
  config.vm.define "toolbox" do |node|
     node.vm.host_name = "toolbox.localhost"
     node.vm.provider :virtualbox do |domain|
         domain.cpus = 2
         domain.memory = 2048
     end
  end

  # Install python2
  config.vm.provision "shell", inline: "yum install -y python2 python-simplejson libselinux-python"

  # Launch Ansible Playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "toolbox.yml"
    ansible.inventory_path = "inventory"
  end

end
