# -*- mode: ruby -*-
# vi: set ft=ruby :

system("ansible-galaxy install -r ../roles/requirements.yml -p ../roles/ --force")
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.provider "virtualbox"
  config.vm.network :private_network, ip: "10.42.0.41"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-hostmanager")
      config.hostmanager.enabled = true
      config.hostmanager.manage_host = true
  end

  # Create the "toolbox" box
  config.vm.define "toolbox" do |node|
     node.vm.host_name = "toolbox.localhost"
     node.vm.provider :virtualbox do |domain|
         domain.cpus = 2
         domain.memory = 2048
     end
  end

  # Install python2
  config.vm.provision "shell", inline: "yum install -y python2 python-simplejson libselinux-python"

  # Launch Ansible Playbook
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
  end

end
